# ===========================================
# 공통 설정 (모든 환경에서 사용)
# ===========================================
spring:
  application:
    name: desolo

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false


  config:
    import: "optional:file:.env[.properties]"

server:
  port: ${SERVER_PORT:8080}